name: prepare

on:
  workflow_call:
    secrets:
      pat_token:
        required: false

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  prepare-ieee:
    runs-on: ubuntu-latest
    needs: prepare
    concurrency:
      group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    steps:
      - run: mkdir ieee

      - uses: actions/checkout@v3
        with:
          repository: metanorma/ieee-stl
          token: ${{ secrets.pat_token || github.token }}
          path: ieee/stl

      - uses: actions/checkout@v3
        with:
          repository: metanorma/mn-samples-ieee
          path: ieee/samples

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.prepare.outputs.default-ruby-version }}
          bundler-cache: true
          working-directory: ieee/samples

      - uses: actions-mn/site-gen@v1
        with:
          source-path: ieee/samples
          use-bundler: true
          agree-to-terms: true

      - uses: actions/upload-artifact@v3
        with:
          name: ieee-test-input
          path: |
            ieee/stl/standards-1-7-DTD/standards-1-7-dtd/
            ieee/samples/site/documents/p987.6/document.xml
