name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:

jobs:
  prepare-ieee:
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    steps:
      - run: mkdir ieee

      - uses: actions/checkout@v3
        with:
          repository: metanorma/ieee-stl
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          path: ieee/stl

      - uses: actions/checkout@v3
        with:
          repository: metanorma/mn-samples-ieee
          path: ieee/samples

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ieee/samples

      - uses: actions-mn/cli/site-gen@main
        with:
          source-path: ieee/samples
          use-bundler: true
          agree-to-terms: true

      - uses: actions/upload-artifact@v3
        with:
          name: ieee-test-input
          path: |
            ieee/stl/standards-1-7-DTD/standards-1-7-dtd/
            ieee/samples/site/documents/p987.6/document.xml

  rake:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ matrix.ruby }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    needs: [ prepare-ieee ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        ruby: [ '3.1', '3.0', '2.7' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: actions/download-artifact@v3
        with:
          name: ieee-test-input
          path: ieee

      - run: ls -R ieee

      - run: bundle exec rake
