name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  prepare-ieee:
    uses: ./.github/workflows/prepare.yml
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

  rake:
    name: Test on Ruby ${{ matrix.ruby.version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    needs: [prepare, prepare-ieee]
    if: needs.prepare.outputs.push-for-tag != 'true'

    concurrency:
      group: '${{ github.workflow }}-${{ matrix.os }}-${{ matrix.ruby.version }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    continue-on-error: ${{ matrix.ruby.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.version }}
          bundler-cache: true
          rubygems: ${{ matrix.ruby.rubygems }}

      - uses: actions/download-artifact@v3
        with:
          name: ieee-test-input
          path: ieee

      - run: bundle exec rake
