name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/mnconvert ]

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  prepare-ieee:
    uses: ./.github/workflows/prepare.yml
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

  tag_repo:
    runs-on: ubuntu-latest
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    needs: [ prepare, prepare-ieee ]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: ieee-test-input
          path: ieee

      - run: |
          git config --global user.name "metanorma-ci"
          git config --global user.email "metanorma-ci@users.noreply.github.com"

      - run: echo mnconvert_VERSION=${mnconvert_TAG#*/v} >> ${GITHUB_ENV}
        env:
          mnconvert_TAG: ${{ github.event.client_payload.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.prepare.outputs.default-ruby-version }}
          bundler-cache: true

      - run: rm -f bin/mnconvert.jar

      - run: bundle exec rake

      - run: |
          gem install gem-release
          gem bump --version ${mnconvert_VERSION} --no-commit

      - name: Push commit and tag
        run: |
          git add -u bin/mnconvert.jar lib/mnconvert/version.rb
          git commit -m "Bump version to ${mnconvert_VERSION}"
          git tag v${mnconvert_VERSION}
          git push origin HEAD:${GITHUB_REF} --tags

      - if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        with:
          assignees: CAMOBAP
          update_existing: true
          search_existing: all