name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/mnconvert ]

jobs:
  prepare-ieee:
    uses: ./.github/workflows/prepare.yml
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

  tag_repo:
    runs-on: ubuntu-latest
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    needs: [ prepare-ieee ]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - run: |
          git config --global user.name "metanorma-ci"
          git config --global user.email "metanorma-ci@users.noreply.github.com"

      - run: echo mnconvert_VERSION=${mnconvert_TAG#*/v} >> ${GITHUB_ENV}
        env:
          mnconvert_TAG: ${{ github.event.client_payload.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - run: gem install gem-release

      - run: gem bump --version ${mnconvert_VERSION} --no-commit

      - run: |
          rm -f bin/mnconvert.jar
          bundle exec rake bin/mnconvert.jar

      - uses: actions/download-artifact@v3
        with:
          name: ieee-test-input
          path: ieee

      - run: bundle exec rake

      - name: Push commit and tag
        run: |
          git add -u bin/mnconvert.jar lib/mnconvert/version.rb
          git commit -m "Bump version to ${mnconvert_VERSION}"
          git tag v${mnconvert_VERSION}
          git push origin HEAD:${GITHUB_REF} --tags
